## The Tensorflow Trials

For much of the past week, you've been using tensors with your Deep Learning models. Over the course of today's challenges, you'll be manipulating tensors extensively and working with some unconventional model architectures. 


In this warm up, you'll be introduced to some new methods. 

All the methods here are going to make tackling challenges later in the day 100x easier, so if you do get stuck later on, make sure you come back here to see how you achieved the right answers. 

In [1]:
import tensorflow as tf

2025-04-13 11:32:42.136294: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-04-13 11:32:42.664855: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


A) Use `tf.ones` to create a tensor `a` filled with ones of shape (3,3).

In [2]:
a = tf.ones((3, 3))

2025-04-13 11:33:10.792430: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
a


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

B) Use tf.expand_dims to make `a` an object of shape (1,3,3) called `b`.

In [4]:
b = tf.expand_dims(a, axis=0)

In [5]:
b

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

C) Create a tensor `c` filled with zeroes of size (9,1)

In [7]:
c = tf.zeros((9, 1))

In [8]:
c

<tf.Tensor: shape=(9, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>

D) Reshape `c` to be of shape (1, 3, 3). Name it `d`.

In [10]:
d = tf.reshape(c, (1, 3, 3))

In [11]:
d

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

E) Use `tf.matmul` to matrix multiply `b` and `d` with each other and now assign the tensor to `e`. 

In [13]:
e = tf.matmul(b, d)

In [14]:
e

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

F) Below is a `numpy` array. Convert it to a tensor named `array_tensor`. Then use `tf.cast` to ensure it is of dtype `float` not `int`. Assign the result to `f`.

In [15]:
import numpy as np

In [16]:
array = np.array([[
    [1,2,3],
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])

In [18]:
array_tensor = tf.convert_to_tensor(array)
f = tf.cast(array_tensor, dtype=tf.float32)

In [19]:
f

<tf.Tensor: shape=(1, 4, 3), dtype=float32, numpy=
array([[[1., 2., 3.],
        [1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]], dtype=float32)>

G) Select the values in the __last column__ of `f` and save this to `g`. To be clear, `g` should have shape (4,) and contain the values `3,3,6,9`. 

In [21]:
g = tf.squeeze(f[:, :, -1])

In [22]:
g

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([3., 3., 6., 9.], dtype=float32)>

H) Expand the dimensions of g so that it's of shape (4,1). Assign this to `h`.

In [24]:
h = tf.expand_dims(g, axis=-1)

In [25]:
h

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[3.],
       [3.],
       [6.],
       [9.]], dtype=float32)>

H) Multiply e with f, using `tf.matmul` with the optional `transpose_b` argument (`e` must come first in your positional arguments, then `f`). Assign this to `h`.

In [27]:
h = tf.matmul(e, f, transpose_b=True)

In [28]:
h

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

I) Create a `(10,10)` tensor filled with ones. Then use `tf.linalg.band_part()` to mask out the upper triangle of the matrix (i.e. the upper triangle should all be 0s). Assign to `i`.

In [30]:
i = tf.linalg.band_part(tf.ones((10, 10)), -1, 0)

In [31]:
i

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

J) Take the `number_list` below and make it a tensor. Assign it to `j`.

In [ ]:
number_list = [1,2,3,4,8]
j = tf.convert_to_tensor(number_list)

In [35]:
j

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 8], dtype=int32)>

K) Use `tf.expand_dims` to make `j` into a tensor of shape (1,5). Assign to `k`.

In [38]:
k = tf.expand_dims(j, axis=0)

In [39]:
k

<tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[1, 2, 3, 4, 8]], dtype=int32)>

L) Use `tf.tile` to repeat `k` 50 times, with an eventual shape of `(50,5)`. Assign to `l`.

In [41]:
l = tf.tile(k, [50, 1])

In [42]:
l

<tf.Tensor: shape=(50, 5), dtype=int32, numpy=
array([[1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 

M) Use a simple Boolean statement to create a tensor containing `True` values for where `l` is 3  and `False` for where it is not 3. Assign to `m`

In [44]:
m = l == 3

In [45]:
m

<tf.Tensor: shape=(50, 5), dtype=bool, numpy=
array([[False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, F

N) Divide every value in you variable `l` (read as "L") by 3. Assign to `n`.

In [47]:
n = l / 3

In [48]:
n

<tf.Tensor: shape=(50, 5), dtype=float64, numpy=
array([[0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333

O) Use `tf.concat()` to take the list of two tensors below of shape (5,5) and (5,5) each and turn them into a final tensor of shape (10,5). Assign to `o`. Think carefully about the concation axis.

In [49]:
tensor_list = [tf.ones((5,5)), tf.ones((5,5))]

In [51]:
o = tf.concat(tensor_list, axis=0)

### Check your answers

In [52]:
from nbresult import ChallengeResult

result = ChallengeResult('tensors',
                            a = a,
                            b = b,
                            c = c,
                            d_shape = d.shape,
                            e = e,
                            f = f,
                            g = g,
                            h = h,
                            i = i,
                            j = j,
                            k = k,
                            l = l,
                            m = m,
                            n = n,
                            o_shape = o.shape
)

result.write()
print(result.check())


============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.1.3, pluggy-1.0.0 -- /home/alrash/.pyenv/versions/lewagon/bin/python
cachedir: .pytest_cache
rootdir: /home/alrash/code/Mjeed42/06-Deep-Learning/05-Transformers/data-tensor-trials/tests
plugins: anyio-3.6.2, typeguard-2.13.3, asyncio-0.19.0
asyncio: mode=strict
collecting ... collected 15 items

test_tensors.py::TestTensors::test_a PASSED                              [  6%]
test_tensors.py::TestTensors::test_b PASSED                              [ 13%]
test_tensors.py::TestTensors::test_c PASSED                              [ 20%]
test_tensors.py::TestTensors::test_d_shape PASSED                        [ 26%]
test_tensors.py::TestTensors::test_e PASSED                              [ 33%]
test_tensors.py::TestTensors::test_f PASSED                              [ 40%]
test_tensors.py::TestTensors::test_g PASSED                              [ 46%]
test_tensors.py::Te

### Great work 🔥

Now it's time to get stuck into some modelling!